services:
  postgres:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: arcade
      POSTGRES_USER: arcade
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  arcade:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - postgres
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
